spring.datasource.url=jdbc:postgresql://localhost:5432/skillforge
spring.datasource.username=skillforge_user
spring.datasource.password=skillforge_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
